name: ChickenOut
main: net.novauniverse.games.chickenout.NovaChickenOut
description: Novauniverse Chickenout
version: 1.0
depend: [NovaCore, NovaCoreGameEngine]
softdepend: [NovaGamesTarget]
api-version: 1.13